# The configurations you want to execute
# That is, a combination of operating system and python version
# Please add or remove for your needs.
# Check all possible values for python in here: https://docs.travis-ci.com/user/languages/python/
# See how to further configure the matrix of combinations in here: https://docs.travis-ci.com/user/multi-os/
language: generic

# Uncomment if you need super powers (e.g., for apt-get)
# sudo: require

# To use other python versions in osx, set the PYTHON variable with the version supported by pyenv.
# Check available versions with `pyenv install --list'.
# We use in this example python >=3.4 because matplotlib requires it
os: linux

install:
  - . ./scripts/ensure_latex.sh
  - ./scripts/ensure_book_dependencies.sh

# Command to run tests. These are run for each configuration
script:
  - pdflatex paper.tex
deploy:
  provider: releases
  api_key:
    secure: licwKC0Udh7AVfG2YlhOqhO/zFYgAQVLVeJ7/yQM0PGrXtmWvXV7utsG/2WesigEpdjHoemGXda8FzwDHQcxE8I6f3Vk1CWYfux+ykrTY6C75vLUcRlB9MUnDvi/T/Oi3kgrDsBn1dOzwK9mUpcImHNPpNp+3W3f8WKJIhdv8696faRr90FP8IbScPOcgUEEYZ5SAyBlU5184Fzo17s144YFuN4YfnAm7qoynFUw8sDwUDO5wlb4KtCZ4+U3dh75eShx/qMmJyD0WLqVdHrJG0S0SkzZXx52voZgt4ORdrNRCW6J1QI8GEOIAttxMVcEHcTzGB7w4sqkGIwZ86akmznQo+wn1TlhOL7TddxQuBV/sh0zRlHoG/Vom7LpHsJQxWg2TGvVaPBzVta+OvyveErEXcvDn+qtVszNwq83mkyEhMdFZr0tsXKjvMtLiknIEiSmaPEMv+4S9OpfwllE6ipHai7OD2mRT/Wjai4ohcR83e7IwaZ3gNbrhKe04kwtFlR4GZLpcy72wdxEl+Ec7zLIvwuvOGvZdANbwOC2CyyXUTIzRG5UWBiKIOp4SpgcigzJOzoYQCryBAK3MwqeeO0Ko3xMYM8as57bj9/OhbT+/siLABeKOBxp3bIBsYWIlpK8LWC4J7z4sUN08SlOGCp9RWpz+xdIqF1AyZnZCyA=
  file: paper.pdf
  skip_cleanup: true
  on:
    repo: CRIStAL-Sigma/latex-travis-test
    tags: true
